## 학습목표
 1. numpy에서 자주 사용되는 함수들을 사용해보기

In [1]:
import numpy as np

#### numpy documentation
 - [numpy 공식 문서 링크](https://www.numpy.org/devdocs/reference/)
 - numpy에서 제공되는 함수등에 대한 문서

In [2]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.01766806 0.78036374 0.76020624 0.69150688 0.78333687]
 [0.79038095 0.51889928 0.82290634 0.85262534 0.85314999]
 [0.56926429 0.88610108 0.66843549 0.09049836 0.59402274]]


#### 연산 함수
 - add, substract, multiply, divide

In [3]:
np.add(x, y)

array([[ 0.01766806,  1.78036374,  2.76020624,  3.69150688,  4.78333687],
       [ 5.79038095,  6.51889928,  7.82290634,  8.85262534,  9.85314999],
       [10.56926429, 11.88610108, 12.66843549, 13.09049836, 14.59402274]])

In [4]:
np.divide(x, y)

array([[  0.        ,   1.28145369,   2.63086503,   4.3383516 ,
          5.1063599 ],
       [  6.32606341,  11.56293759,   8.50643587,   9.38278466,
         10.54914154],
       [ 17.56653302,  12.4139337 ,  17.95236815, 143.64900582,
         23.56812115]])

In [5]:
x + y

array([[ 0.01766806,  1.78036374,  2.76020624,  3.69150688,  4.78333687],
       [ 5.79038095,  6.51889928,  7.82290634,  8.85262534,  9.85314999],
       [10.56926429, 11.88610108, 12.66843549, 13.09049836, 14.59402274]])

In [6]:
x / y

array([[  0.        ,   1.28145369,   2.63086503,   4.3383516 ,
          5.1063599 ],
       [  6.32606341,  11.56293759,   8.50643587,   9.38278466,
         10.54914154],
       [ 17.56653302,  12.4139337 ,  17.95236815, 143.64900582,
         23.56812115]])

#### 통계 함수
 - 평균, 분산, 중앙, 최대, 최소값 등등 통계 관련된 함수가 내장

In [7]:
print(y)

[[0.01766806 0.78036374 0.76020624 0.69150688 0.78333687]
 [0.79038095 0.51889928 0.82290634 0.85262534 0.85314999]
 [0.56926429 0.88610108 0.66843549 0.09049836 0.59402274]]


In [8]:
np.mean(y)

0.6452910441771508

In [9]:
y.mean()

0.6452910441771508

In [10]:
np.max(y)

0.886101075080775

In [11]:
np.argmax(y)

11

In [12]:
np.var(y), np.median(y), np.std(y)

(0.06506985793532696, 0.7602062352692948, 0.2550879415717783)

#### 집계함수
 - 합계(sum), 누적합계(cumsum) 등등 계산 가능

In [14]:
y

array([[0.01766806, 0.78036374, 0.76020624, 0.69150688, 0.78333687],
       [0.79038095, 0.51889928, 0.82290634, 0.85262534, 0.85314999],
       [0.56926429, 0.88610108, 0.66843549, 0.09049836, 0.59402274]])

In [15]:
np.sum(y, axis=None)

9.679365662657261

In [16]:
np.cumsum(y)

array([0.01766806, 0.7980318 , 1.55823804, 2.24974492, 3.03308179,
       3.82346274, 4.34236202, 5.16526836, 6.01789371, 6.8710437 ,
       7.44030799, 8.32640906, 8.99484455, 9.08534292, 9.67936566])

#### any, all 함수
 - any: 특정 조건을 만족하는 것이 하나라도 있으면 True, 아니면 False
 - all: 모든 원소가 특정 조건을 만족한다면 True, 아니면 False

In [17]:
z = np.random.randn(10)
print(z)

[ 0.6868678  -0.61159475 -0.65439718 -0.50581019 -0.29121378  1.05647992
  0.48712314 -2.24220664  0.48198048  0.65968354]


In [18]:
z > 0

array([ True, False, False, False, False,  True,  True, False,  True,
        True])

In [19]:
np.any(z > 0)

True

In [20]:
np.all(z != 0)

True

#### where 함수
 - 조건에 따라 선별적으로 값을 선택 가능
 - 사용 예) 음수인경우는 0, 나머지는 그대로 값을 쓰는 경우

In [21]:
z = np.random.randn(10)
print(z)

[ 0.80556528 -1.87040951 -2.09947042 -1.39889212 -0.44692443 -1.76322499
 -0.31471696  1.06782497  0.39411349 -1.26564542]


In [22]:
np.where(z > 0, z, 0)

array([0.80556528, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 1.06782497, 0.39411349, 0.        ])