## 학습목표
 1. linalg 서브모듈 함수 활용여 선형대수 연산하기

In [1]:
import numpy as np

#### np.linalg.inv
 - 역행렬을 구할 때 사용
 - 모든 차원의 값이 같아야 함

In [2]:
x = np.random.rand(3, 3, 3)
print(x)

np.matmul(x, np.linalg.inv(x))
x @ np.linalg.inv(x)

[[[0.41033725 0.89004971 0.74571142]
  [0.42069546 0.7625522  0.15570852]
  [0.10632061 0.09742069 0.51161825]]

 [[0.26808777 0.98637659 0.41855546]
  [0.05781689 0.88368283 0.51892886]
  [0.22074905 0.2680224  0.03515179]]

 [[0.93442884 0.14120058 0.5576574 ]
  [0.08889946 0.66518961 0.04895896]
  [0.59606728 0.08786864 0.27279549]]]


array([[[ 1.00000000e+00, -1.28460551e-16,  1.76222332e-16],
        [-4.47400527e-17,  1.00000000e+00, -4.15879947e-16],
        [-8.43278682e-17, -6.59584024e-17,  1.00000000e+00]],

       [[ 1.00000000e+00, -5.02850443e-17, -1.56094625e-15],
        [ 7.55828576e-16,  1.00000000e+00,  8.48709034e-16],
        [-5.48041178e-16, -3.32342438e-16,  1.00000000e+00]],

       [[ 1.00000000e+00, -1.43410401e-18,  4.11174572e-16],
        [-4.95433814e-17,  1.00000000e+00,  2.89509817e-17],
        [ 1.36441023e-16,  4.03046995e-18,  1.00000000e+00]]])

#### np.linalg.solve
 - Ax = B 형태의 선형대수식 솔루션을 제공
 - 예제) 호랑이와 홍합의 합 : 25 호랑이 다리와 홍합 다리의 합은 64
   - x + y = 25
   - 2x + 4y = 64
   
 $$\begin{pmatrix} 1 & 1 \\ 2 & 4 \end{pmatrix}\begin{pmatrix} x \\ y \end{pmatrix}= \begin{pmatrix} 25 \\ 64 \end{pmatrix}$$


In [3]:
A = np.array([[1, 1], [2, 4]])
B = np.array([25, 64])

x = np.linalg.solve(A, B)
print(x)

np.allclose(A@x, B)

[18.  7.]


True